import React from "react";
import styles from "../../styles/layout/layout.module.css";
import { Noto_Sans } from "next/font/google";
import Header from "../common/Header";
import Footer from "../common/Footer";
import Head from "next/head";

export default function Layout({ children, metaTitle }) {
  return (
    <div className="wrap">
      <Head>
        <title>{metaTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      {children}
      <Footer></Footer>
    </div>
  );
}
